### ISSUE TITLE
"Memories" sollte auch uneingeloggt zugänglich sein

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#11]
Ruft man memories.php?username=Adi%26Ko auf, ohne eingeloggt zu sein, kommt man auf die notLoggedIn Seite. Das ist schade, könnte man die nicht auch uneingeloggt anzeigen?

**Comment by mircowidmer** [comment]
Fixed!

**Comment by wild8oar** [comment]
Super, danke für die schnelle Reaktion! :)
