### ISSUE TITLE
Detail: Found count für musharosky ist falsch

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#12]
Die Anzahl Finds für musharosky wird mit 622 angezeigt, zufällig genau die selbe Zahl wie Adi&Ko. bei rubik wird aber eine andere Zahl (1641) angezeigt.

**Comment by mircowidmer** [comment]
Fixed! War eine Kombination von falschem DB-Wert und nicht so korrektem Crawling...
