### ISSUE TITLE
Falscher Cache Typ

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#15]
Der Cache "Greifensee Serie #3 Ebmatingen" wird als Multi angezeigt, ist aber ein Tradi...
https://www.geocaching.com/seek/cache_details.aspx?wp=GC1XB6X&title=greifensee-serie-3-ebmatingen

**Comment by mircowidmer** [comment]
Gefixt! So ein Beta-Tester ist in der Tat eine saugute Sache :)

**Comment by wild8oar** [comment]
Wow, war das, weil der in der List "Multi-cache Serie Greifensee" ist??

**Comment by mircowidmer** [comment]
Genau das war das Problem.
