### ISSUE TITLE
Cache aus Founds verschwunden

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#16]
Hm, seit dem Tradi-als-Multi Fix ist "Greifensee Serie #3 Ebmatingen" nicht mehr bei meinen Funden mit dabei. ich sehe keine "You found this one too" und auf meiner Karte ist er auch nicht eingezeichnet.

**Comment by mircowidmer** [comment]
Das liegt an meinem etwas voreiligen DB-Fix von gestern ;-) Am einfachsten lädst du einfach kurz deine Finds hoch, das geht am schnellsten.

**Comment by mircowidmer** [comment]
So, habs nun db-mässig wieder gefixt!
