### ISSUE TITLE
Flag Icons auf On This Day Page fehlen

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#19]
Auf der On This Day Page gibt es keine Flag Icons mehr.
https://mirco-widmer.ch/geonews/memories.php
Die Img-Src ist z.B. https://mirco-widmer.ch/geonews/res/icons/countries/-1.gif

**Comment by mircowidmer** [comment]
Das Problem ist die Parameter-Reihenfolge:

#### memories.php (falsch):
printLogEntry(false, $name, $gc, $type, $created, $log, $logId, $username, $logType, $difficulty, $terrain, $country, $favorites, $url, array(), $address, $district, $lat, $lon, $avatar);

#### index.php (korrekt):
printLogEntry(false, $name, $gc, $type, $created, $log, $logId, $username, $logType, $difficulty, $terrain, $favorites, $country, $url, $sessionResults, $address, $district, $lat, $lon, $avatar);

Vertauscht sind country und favorites. Abgesehen davon, ist das sowieso wunderschöner Code!

**Comment by mircowidmer** [comment]
Im übrigen musst du natürlich geonews.li einbinden und nicht mehr mirco-widmer.ch/geonews! Nämlich!

**Comment by wild8oar** [comment]
Logisch, da sieht man ja sofort, dass die Reihenfolge nicht stimmt! 

Habe meine Booksmarks/Iframe-src geändert. :)
