### ISSUE TITLE
iframe Option

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#5]
![iframe](https://cloud.githubusercontent.com/assets/16754669/12386038/172bb776-bdc2-11e5-8e05-dc3610e9790f.png)
Es sollte eine Option für Verwendung in einem iframe geben, z.B. mit URL-Parameter iframe=true oder so ähnlich. Wenn diese Option gesetzt ist, soll die Titelzeile/Navigation nicht angezeigt werden und auf der "today" Seite auch die Benutzersuche nicht sichtbar sein.

**Comment by mircowidmer** [comment]
check it out mit "embedded=true"

**Comment by wild8oar** [comment]
Perfekt! :)
