### ISSUE TITLE
Geographische Information

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#6]
Bei den Logs könnte man auch Land (mit Flagicon), und die "sub-nationale Einheit" (Kanton, Bundesland etc) angeben. Damit man leicht so kann wo seine Freunde unterwegs sind.

**Comment by mircowidmer** [comment]
http://www.freeflagicons.com könnte man vielleicht dafür verwenden.

**Comment by wild8oar** [comment]
Du kannst auch die Flaggen einfach aus Wikipedia nehmen (die Kantone von
hier:
https://de.wikipedia.org/wiki/Liste_der_Wappen_und_Fahnen_der_Schweizer_Kantone)
und dann mit einer CSS Klasse "schöne" Icons daraus machen, z.B. so

.flagSmall {
  border-radius: 7px;
  border: 1px solid black;
  display: inline-block;
  width: 20px;
  height: 20px;
  background-size: cover;
  background-position: center center;
  background-repeat: no-repeat;
}

**Comment by mircowidmer** [comment]
Problematisch ist die Tatsache, dass ich uneingeloggt nicht an die Location eines Caches komme :/ Wenn das Login einfacher machbar wäre, ginge vieles einfacher.

**Comment by wild8oar** [comment]
Zumindest bei nicht-Premiums siehst du Land und Region. Im GPX steht dann
schon alles, nehme ich an?

2016-01-18 19:08 GMT+01:00 Mirco Widmer <notifications@github.com>:

**Comment by wild8oar** [comment]
Ui, habe gerade die geocaching.com Loginseite angeschaut. Sieht so aus,
also ob du da (obfuscated) JavaScript ausführen musst? Ganz schön gemein....

2016-01-18 20:00 GMT+01:00 Adrian Schneider <schneadr@gmail.com>:

**Comment by mircowidmer** [comment]
Bzgl state: Ein paar Beispiele was so im GPX drin steht:
<groundspeak:state>Region Zuerich (ZH)</groundspeak:state>
<groundspeak:state>Ostschweiz (SG/SH/TG/AI/AR/GL)</groundspeak:state>
<groundspeak:state>Graubuenden (GR)</groundspeak:state>
<groundspeak:state>Nordwestschweiz (AG/BL/BS)</groundspeak:state>
<groundspeak:state>Zentralschweiz (ZG/SZ/LU/UR/OW/NW)</groundspeak:state>
Irgendwie doof. Was vielleicht fast schlauer wäre: Beim Import aufgrund der GPS-Koordinaten irgendwie via Google Maps einen Kantons-Lookup zu machen anstatt das hier zu normalisieren... Stelle nun mal die Länder dar :)

**Comment by wild8oar** [comment]
Das GSAK berechnet Kantone (und andere sub-nationale Einheiten) aufgrund
von Polynomfiles. Muss mal schauen, ob man die "mitbenutzen" kann. :)

2016-01-18 22:47 GMT+01:00 Mirco Widmer <notifications@github.com>:

**Comment by wild8oar** [comment]
Hm, netter Versuch, aber das Icon ist leicht zu gross :P

![flag_big](https://cloud.githubusercontent.com/assets/16754669/12412931/3ccee16e-be8b-11e5-87c1-1bf4df616b94.png)

**Comment by wild8oar** [comment]
Wow, mit Gemeindeinformation und Kantonswappen! Mega cool! Wie hast du das denn gemacht?

**Comment by mircowidmer** [comment]
Hello!

Das geht ja wirklich zackig bei dir :P
Da ich nun einloggen kann, komme ich auch beim Crawlen an die Location ran. Und dann lasse ich jeden Besucher etwas mithelfen via Google einen Reverse Lookup zu machen um an die 'Adresse' zu kommen :)

**Comment by mircowidmer** [comment]
Auch lustig. Bei https://www.geocaching.com/geocache/GC50M91_the-shortest-street-in-porto-afonso-martins-alho klappt ganz einfach der Reverse Lookup nicht via Google ... https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse und wenn man dort die Koordinate 41.1446, -8.6123 eingibt, findet Google nichts, bei 41.1446, -8.6103 klappts jedoch... Wart ihr in einem Safe House des Militärs?

**Comment by wild8oar** [comment]
Ha, lustig! Nähme mich mal Wunder, auf was für Daten dieser Lookup basiert...
Aber wie du auf Google Maps sehen kannst, es war eine ganz normale Strasse, mitten in der Stadt: 
https://www.google.ch/maps/place/41%C2%B008'40.6%22N+8%C2%B036'44.3%22W/@41.1446,-8.6144887,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0?hl=en
