### ISSUE TITLE
Upload funktioniert nicht

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#7]
Habe mit angehängtem GPX (ungezippt) versucht. Alte und Premium-Caches haben immer noch keine Flagge.
[11457527.zip](https://github.com/mircowidmer/geonews/files/97358/11457527.zip)

**Comment by mircowidmer** [comment]
In der Tat! Skandal! Schau mir das zu Hause an.

**Comment by mircowidmer** [comment]
fixed!
