### ISSUE TITLE
Map unvollständig

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#8]
Auf "meiner" Map (https://mirco-widmer.ch/geonews/all.php?username=Adi%26Ko) sind die letzten 4 Finds nicht eingezeichnet (sollten in Winterthur Seen, d,h. "rechts" in Winterthur) sein...

**Comment by mircowidmer** [comment]
Ja, das liegt ziemlich sicher daran, dass ich bei diesen vier geparsten Einträgen keine Location erwischte und der Upload kaputt ist.

**Comment by mircowidmer** [comment]
fixed!

**Comment by wild8oar** [comment]
cool, jetzt kann ich endlich sehen, wo ich das Wochenende verbracht habe. :)

**Comment by mircowidmer** [comment]
Sau-umständliche Variante :P Aber wieso einfach, wenns auch kompliziert geht? :)
