### ISSUE TITLE
embedded-Mode leicht broken

### ISSUE THREAD

**Issue by wild8oar** [mircowidmer/geonews#9]
![embedded](https://cloud.githubusercontent.com/assets/16754669/12452629/b32da692-bf8f-11e5-9395-fd6412b527ca.png)

**Comment by mircowidmer** [comment]
"kä detail" ;-P Aber klar, du hast recht, hab gestern um Mitternacht nicht mehr alles getestet...

**Comment by mircowidmer** [comment]
fixed!

**Comment by wild8oar** [comment]
danke! :)
